[package]
name = "csv2svg"
version = "0.1.2"
authors = ["dystroy <denys.seguret@gmail.com>"]
edition = "2018"
repository = "https://github.com/Canop/csv2svg"
description = "take a csv as input and outputs svg"
keywords = ["csv", "svg", "graph", "cli"]
license = "MIT"
readme = "README.md"

[dependencies]
anyhow = "1.0"
argh = "0.1.3"
chrono = "0.4"
cli-log = "0.1"
csv = "1.1"
directories-next = "2.0"
log = "0.4"
num-traits = "0.2.14"
svg = "0.8"

[patch.crates-io]
