[package]
name = "starry"
version = "0.1.2"
authors = ["dystroy <denys.seguret@gmail.com>"]
edition = "2018"
repository = "https://github.com/Canop/starry"
description = "Current stars history tells only half the story"
keywords = ["github", "star", "story", "history", "graph"]
license = "AGPL-3.0"
readme = "README.md"

[dependencies]
anyhow = "1.0"
argh = "0.1.3"
chrono = { version="0.4", features=["serde"] }
cli-log = "0.1"
csv = "1.1"
directories-next = "2.0"
log = "0.4"
num-traits = "0.2.14"
serde = { version = "1.0", features = ["derive"] }
svg = "0.8"

[patch.crates-io]
# byo-graphql = { path = "../byo-graphql" }
